name: Build CTB (Windows)

on:
  workflow_dispatch:   # 手动触发
  push:
    tags:
      - 'v*'           # push tag（如 v1.0.0）时自动触发

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup vcpkg & install GDAL
        uses: lukka/run-vcpkg@v11
        with:
          # 指定要安装的包（可根据需要增删特性）
          vcpkgArguments: install gdal:x64-windows
          vcpkgDirectory: ${{ github.workspace }}/vcpkg

      - name: Configure CMake (Generate)
        shell: pwsh
        run: |
          cmake -S . -B build -G "Ninja" `
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" `
            -DCMAKE_BUILD_TYPE=Release

      - name: Build (CMake)
        shell: pwsh
        run: |
          cmake --build build --config Release

      - name: Collect exe + dependent DLLs
        shell: pwsh
        run: |
          New-Item -Path out -ItemType Directory -Force | Out-Null
          Get-ChildItem -Path build -Filter *.exe -Recurse -ErrorAction SilentlyContinue | Copy-Item -Destination out -Force
          $vcpkgBin = "${{ github.workspace }}\vcpkg\installed\x64-windows\bin"
          if (Test-Path $vcpkgBin) { Copy-Item -Path "$vcpkgBin\*.dll" -Destination out -ErrorAction SilentlyContinue }

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ctb-windows-exes
          path: out
          retention-days: 7

      - name: Create GitHub Release & attach assets (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: out/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
